---
language: node_js
sudo: false
dist: trusty
node_js:
  - "10"

addons:
  chrome: stable

cache:
  yarn: true

branches:
  only:
    - master
    - beta
    - release
    # release branches
    - /^release-.*/
    # npm version tags
    - /^v\d+\.\d+\.\d+/

stages:
  - test
  - additional tests
  - ember version tests
  - name: external partner tests
    if: NOT (branch ~= /^release.*/)
  - name: deploy
    if: type = push AND (branch IN (master, beta, release) OR tag IS present)

jobs:
  fail_fast: true

  include:
    # runs tests with current locked deps and linting
    - stage: test
      name: "Linting"
      if: NOT (branch ~= /^release.*/)
      script:
        - ./bin/lint-features
        - yarn lint:js
    - name: "Basic Tests"
      script: yarn test

    - stage: additional tests
      name: "Optional Features"
      if: NOT (branch ~= /^release.*/)
      install: yarn install
      script: yarn test:optional-features

    - name: "Floating Dependencies"
      install: yarn install --no-lockfile --non-interactive
      script: yarn test

    - name: "Max Transpilation"
      install: yarn install
      env: TARGET_IE11=true
      script: yarn test

    - name: "Production"
      install: yarn install
      script: yarn test:production

    - name: "Node Tests"
      install: yarn install
      script: yarn test:node

    # runs tests against each supported Ember version
    - stage: ember version tests
      name: "Ember LTS 2.16"
      env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - name: "Ember LTS 2.18"
      env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - name: "Ember Release"
      if: NOT (branch ~= /^release.*/)
      env: EMBER_TRY_SCENARIO=ember-release
    - name: "Ember Beta"
      if: NOT (branch ~= /^release.*/)
      env: EMBER_TRY_SCENARIO=ember-beta
    - name: "Ember Canary"
      if: NOT (branch ~= /^release.*/)
      env: EMBER_TRY_SCENARIO=ember-canary

    # runs tests against various open-source projects for early-warning regression analysis
    - stage: external partner tests
      name: "Ember Data Model Fragments"
      script: yarn test-external:model-fragments
    - name: "Ember Observer"
      script: yarn test-external:ember-observer
    - name: "Travis Web"
      script: yarn test-external:travis-web
    - name: "emberaddons.com"
      script: yarn test-external:emberaddons.com
    - name: "Ember Data Change Tracker"
      script: yarn test-external:ember-data-change-tracker
    - name: "ember-m3"
      script: yarn test-external:ember-m3
    - name: "Ember Data Storefront"
      script: yarn test-external:storefront
    - name: "Ember Data Factory Guy"
      script: yarn test-external:factory-guy
    - name: "Ilios Frontend"
      script: yarn test-external:ilios-frontend
    - name: "Ember Resource Metadata"
      script: yarn test-external:ember-resource-metadata
    - name: "Ember Data Relationship Tracker"
      script: yarn test-external:ember-data-relationship-tracker

    - stage: deploy
      name: "Publish"
      install: yarn install
      script:
        - node_modules/.bin/ember try:reset
        - yarn build:production


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install
  - yarn add global bower

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

env:
  global:
  - BROCCOLI_ENV="production"
  - S3_BUILD_CACHE_BUCKET=emberjs-build-cache
  - S3_BUCKET_NAME=builds.emberjs.com
  - secure: ! 'S+DIdzEPvqQenk1cFq5UjbkoEKDY4j3E/g+Wlz798xxyTkrKQZxoazLXng8I

      gsxElZtB2kpyUq81gWgZcuygO53mcBuCa4rPIsh0Di6Ik+HDELSFVZ4EN4NK

      z9yP6D7pMY+RnlSvErf3OXSzrxkDcXDxCU4ljBJl1rNBbtAOu5E='
  - secure: ! 'YjnT2cF8K0M2fSkab+PY3j8XzumBrjzeGsAN4jtyw4shqnywFaE68qO1IIjY

      UvaE/CbWMxO/6FszR02gJHaF+YyfU5WAS0ahFFLHuC1twMtQPxi+nScjKZEs

      kLwKiKgRNhindV3WvbUcoiIrmrgBMCiBRRd4eyVBlhbZ8RTo1Ig='

  - secure: "hJZXijsot2wMiMsxbDImH+nB5v77a7O7lQ7bicOQEQxmnTtXSvqfa4X4vQ/d4o7NNYYYHUuOpyILgRV+arqI6UOi7XEVGka/7M5q58R5exS6bk0cY0jnpUhUVW/8mpKEUgcVeE6mIDWaR090l3uaT2JhU/WSLkzbj45e38HaF/4="
