---
language: node_js
sudo: false
dist: trusty
node_js:
  - "4"

addons:
  chrome: stable

cache:
  yarn: true

branches:
  only:
    - master
    - beta
    - release
    # npm version tags
    - /^v\d+\.\d+\.\d+/

stages:
  - test
  - additional tests
  - older version tests
  - name: deploy
    if: type = push AND (branch IN (master, beta, release) OR tag IS present)

jobs:
  fail_fast: true

  include:
    # runs tests with current locked deps and linting
    - stage: test
      env: NAME=test                  # used only to make Travis UI show description
      script:
        - ./bin/lint-features
        - yarn test

    - stage: additional tests
      env: NAME=optional-features     # used only to make Travis UI show description
      install: yarn install
      script: yarn test:optional-features

    - env: NAME=floating dependencies # used only to make Travis UI show description
      install: yarn install --no-lockfile --non-interactive
      script: yarn test

    - env: NAME=production            # used only to make Travis UI show description
      install: yarn install
      script: yarn test:production

    - env: NAME=node-tests            # used only to make Travis UI show description
      install: yarn install
      script: yarn test:node

    # runs tests against each supported Ember version
    - stage: older version tests
      env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

    - stage: deploy
      env: NAME=publish                # used only to make Travis UI show description
      install: yarn install
      script:
        - node_modules/.bin/ember try:reset
        - yarn build:production
        - "./bin/publish-builds"


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

env:
  global:
  - BROCCOLI_ENV="production"
  - S3_BUILD_CACHE_BUCKET=emberjs-build-cache
  - S3_BUCKET_NAME=builds.emberjs.com
  - secure: ! 'S+DIdzEPvqQenk1cFq5UjbkoEKDY4j3E/g+Wlz798xxyTkrKQZxoazLXng8I

      gsxElZtB2kpyUq81gWgZcuygO53mcBuCa4rPIsh0Di6Ik+HDELSFVZ4EN4NK

      z9yP6D7pMY+RnlSvErf3OXSzrxkDcXDxCU4ljBJl1rNBbtAOu5E='
  - secure: ! 'YjnT2cF8K0M2fSkab+PY3j8XzumBrjzeGsAN4jtyw4shqnywFaE68qO1IIjY

      UvaE/CbWMxO/6FszR02gJHaF+YyfU5WAS0ahFFLHuC1twMtQPxi+nScjKZEs

      kLwKiKgRNhindV3WvbUcoiIrmrgBMCiBRRd4eyVBlhbZ8RTo1Ig='

  - secure: "hJZXijsot2wMiMsxbDImH+nB5v77a7O7lQ7bicOQEQxmnTtXSvqfa4X4vQ/d4o7NNYYYHUuOpyILgRV+arqI6UOi7XEVGka/7M5q58R5exS6bk0cY0jnpUhUVW/8mpKEUgcVeE6mIDWaR090l3uaT2JhU/WSLkzbj45e38HaF/4="
