---
rvm:
- 1.9.3
install:
- "bin/cached-npm install"
- "bin/cached-bundle install --deployment"
- sudo apt-get update && sudo apt-get install git
script: rake test[all]
after_success: bundle exec rake publish_build
env:
  global:
  - S3_BUILD_CACHE_BUCKET=emberjs-build-cache
  - S3_BUCKET_NAME=builds.emberjs.com
  - secure: ! 'S+DIdzEPvqQenk1cFq5UjbkoEKDY4j3E/g+Wlz798xxyTkrKQZxoazLXng8I

      gsxElZtB2kpyUq81gWgZcuygO53mcBuCa4rPIsh0Di6Ik+HDELSFVZ4EN4NK

      z9yP6D7pMY+RnlSvErf3OXSzrxkDcXDxCU4ljBJl1rNBbtAOu5E='
  - secure: ! 'YjnT2cF8K0M2fSkab+PY3j8XzumBrjzeGsAN4jtyw4shqnywFaE68qO1IIjY

      UvaE/CbWMxO/6FszR02gJHaF+YyfU5WAS0ahFFLHuC1twMtQPxi+nScjKZEs

      kLwKiKgRNhindV3WvbUcoiIrmrgBMCiBRRd4eyVBlhbZ8RTo1Ig='
