---
language: node_js
sudo: false
node_js:
  - "4.2"
before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - npm install -g phantomjs-prebuilt@2

install:
  - npm install --no-optional
  - ./node_modules/.bin/bower install
script:
  - ./bin/lint-features
  - npm run-script test
  - npm run-script test:optional-features
  - npm run-script node-tests
after_success:
  - npm run-script production
  - "./bin/publish-builds"
env:
  global:
  - BROCCOLI_ENV="production"
  - S3_BUILD_CACHE_BUCKET=emberjs-build-cache
  - S3_BUCKET_NAME=builds.emberjs.com
  - secure: ! 'S+DIdzEPvqQenk1cFq5UjbkoEKDY4j3E/g+Wlz798xxyTkrKQZxoazLXng8I

      gsxElZtB2kpyUq81gWgZcuygO53mcBuCa4rPIsh0Di6Ik+HDELSFVZ4EN4NK

      z9yP6D7pMY+RnlSvErf3OXSzrxkDcXDxCU4ljBJl1rNBbtAOu5E='
  - secure: ! 'YjnT2cF8K0M2fSkab+PY3j8XzumBrjzeGsAN4jtyw4shqnywFaE68qO1IIjY

      UvaE/CbWMxO/6FszR02gJHaF+YyfU5WAS0ahFFLHuC1twMtQPxi+nScjKZEs

      kLwKiKgRNhindV3WvbUcoiIrmrgBMCiBRRd4eyVBlhbZ8RTo1Ig='

  - secure: "hJZXijsot2wMiMsxbDImH+nB5v77a7O7lQ7bicOQEQxmnTtXSvqfa4X4vQ/d4o7NNYYYHUuOpyILgRV+arqI6UOi7XEVGka/7M5q58R5exS6bk0cY0jnpUhUVW/8mpKEUgcVeE6mIDWaR090l3uaT2JhU/WSLkzbj45e38HaF/4="
