# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "4.2"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Install PhantomJS
  - choco install phantomjs --version 2.0.0 -y
  - set path=%path%;C:\ProgramData\chocolatey\lib\PhantomJS\tools\
  # Typical npm stuff.
  - md C:\nc
  - npm install -g npm@^2
  # Workaround https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows
  - set PATH=%APPDATA%\npm;%PATH%
  - npm config set cache C:\nc
  - npm version
  - npm install --no-optional
  - npm run bower
# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - npm version
  - cmd: npm run test
  - cmd: npm run test:optional-features
  - cmd: npm run test:production
  - cmd: npm run node-tests

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
