name: Alpha Releases

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Type of Version Bump To Perform'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
  schedule:
    - cron: '0 20 * * 2' # weekly (Tuesday) 12 PM PST
    - cron: '0 20 * * 5' # weekly (Friday) 12 PM PST

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

jobs:
  release:
    name: Run publish script
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 1
          fetch-tags: true
          progress: false
      - name: Check should run if HEAD is untagged
        run: |
          echo "HEAD is $(git name-rev --tags --name-only $(git rev-parse HEAD))"
          if [[ "$(git name-rev --tags --name-only $(git rev-parse HEAD))" != "undefined" ]]; then
            exit 1
          fi
      - uses: ./.github/actions/setup
        with:
          install: true
          repo-token: ${{ secrets.GH_DEPLOY_TOKEN }}
      - name: Make sure git user is setup
        run: |
          git config --local user.email '${{ secrets.GH_DEPLOY_EMAIL }}'
          git config --local user.name '${{ secrets.GH_DEPLOY_NAME }}'
      - name: Publish with script
        run: bun run publish canary -i ${{ github.event.inputs.increment }}
        env:
          FORCE_COLOR: 2
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: tarballs
          path: tmp/tarballs/**/*.tgz
