name: PR

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened]
    branches:
      - main

concurrency:
  group: pr-labels-canary-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  enforce-changelog-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: 'changelog:breaking,changelog:feat,changelog:bugfix,changelog:perf,changelog:cleanup,changelog:deprecation,changelog:doc,changelog:test,changelog:chore,changelog:dependencies'
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label for changelog generation. ['changelog:breaking', 'changelog:feat', 'changelog:bugfix', 'changelog:perf', 'changelog:cleanup', 'changelog:deprecation', 'changelog:doc', 'changelog:test', 'changelog:chore', 'changelog:dependencies']"
  enforce-target-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: ':dart: canary,:dart: beta,:dart: release,:dart: lts,:dart: lts-prev,changelog:dependencies'
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label for what release channels to target. Use the labels `:dart: canary` or `changelog:dependencies` and none of the others in the list if this PR should not be backported. [':dart: canary', ':dart: beta', ':dart: release', ':dart: lts', ':dart: lts-prev']"
  ban-release-branch-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          BANNED_LABELS: 'backport-beta,backport-release,backport-lts,backport-lts-prev,backport-old-release'
          BANNED_LABELS_DESCRIPTION: "The following labels should only be applied to PRs targeting release channel branches that backport a change already on the main branch, remove them.['backport-beta', 'backport-release', 'backport-lts', 'backport-lts-prev', 'backport-old-release']"
